---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - vgmanager.kubotal.io
  resources:
  - lvmvolumegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vgmanager.kubotal.io
  resources:
  - lvmvolumegroups/finalizers
  verbs:
  - update
- apiGroups:
  - vgmanager.kubotal.io
  resources:
  - lvmvolumegroups/status
  verbs:
  - get
  - patch
  - update
