# permissions for end users to edit lvmvolumegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vgop
    app.kubernetes.io/managed-by: kustomize
  name: vgop-lvmvolumegroup-editor-role
rules:
- apiGroups:
  - vgop.kubotal.io
  resources:
  - lvmvolumegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vgop.kubotal.io
  resources:
  - lvmvolumegroups/status
  verbs:
  - get
