---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "vgop.deploymentName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vgop.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "vgop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vgop.labels" . | nindent 8 }}
        {{- include "vgop.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: vgop
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- with .Values.extraEnv }}
          {{- toYaml . | nindent 4 }}
          {{- end }}
          command:
            - {{ default "/vgop" .Values.command }}
          args:
            - --logMode
            - {{ .Values.logger.mode}}
            - --logLevel
            - {{ .Values.logger.level}}
          {{-  range .Values.additionalArgs }}
            - {{ . }}
          {{- end }}
          {{- if not (default false .Values.disableProbes )}}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
        {{- with .Values.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
          securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 12 }}
        {{- if .Values.extraVolumes }}
          volumeMounts:
        {{- range .Values.extraVolumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
        {{- end }}
        {{- end }}
      serviceAccountName: {{ include "vgop.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.extraVolumes }}
      volumes:
      {{- range .Values.extraVolumes }}
        - name: {{ .name }}
          {{- toYaml .volume | nindent 10 }}
      {{- end }}
      {{- end }}
