---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vgop.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vgop.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vgop.roleName" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vgop.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - vgop.kubotal.io
    resources:
      - lvmvolumegroups
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - vgop.kubotal.io
    resources:
      - lvmvolumegroups/finalizers
    verbs:
      - update
  - apiGroups:
      - vgop.kubotal.io
    resources:
      - lvmvolumegroups/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - vgop.kubotal.io
    resources:
      - lvmvolumegroupnodestatuses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - vgop.kubotal.io
    resources:
      - lvmvolumegroupnodestatuses/finalizers
    verbs:
      - update
  - apiGroups:
      - vgop.kubotal.io
    resources:
      - lvmvolumegroupnodestatuses/status
    verbs:
      - get
      - patch
      - update


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vgop.clusterRoleName" .}}
  labels:
    {{- include "vgop.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vgop.roleName" .}}-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vgop.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vgop.roleName" .}}
subjects:
  - kind: ServiceAccount
    name: {{ include "vgop.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vgop.clusterRoleName" .}}-binding
  labels:
    {{- include "vgop.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vgop.clusterRoleName" .}}
subjects:
  - kind: ServiceAccount
    name: {{ include "vgop.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
